### ISSUE TITLE
While running jest  InlineSVG is having an error of 'Not a constructor' in svelte. 

### ISSUE THREAD

**Issue by scottdkey** [robinscholz/svelte-inline-svg#24]
Hey, this package works great except for svelte-jester testing. Not sure if I should be putting this issue there or here.

jest: 27.5.0
svelte-jester: 2.3.1
svelte: 3.44.2
svelte-inline-svg: ^1.1.1
typescript: 4.5.5

I'm not entirely sure what information you need to re-create the issue. 

``` 
TypeError: InlineSVG is not a constructor

      at Array.create_if_block (src/Components/PaymentIcon/PaymentIcon.svelte:237:14)
      at create_fragment (src/Components/PaymentIcon/PaymentIcon.svelte:305:94)
      at init (node_modules/svelte/internal/index.js:1809:37)
      at new PaymentIcon (src/Components/PaymentIcon/PaymentIcon.svelte:411:3)
      at create_fragment (src/Components/PaymentType/PaymentType.svelte:38:16)
      at init (node_modules/svelte/internal/index.js:1809:37)
      at new PaymentType (src/Components/PaymentType/PaymentType.svelte:193:3)
      at render (node_modules/@testing-library/svelte/dist/pure.js:81:21)
      at Object.<anonymous> (src/Components/PaymentType/PaymentType.spec.ts:19:33)
```
      
      
      -- PaymentIcon.svelte --
```
<script lang="ts">

  import "../../SharedStyles/paymentIcon.scss";

  import Amex from "../../Icons/Amex.svg";
  import Discover from "../../Icons/Discover.svg";
  import Mastercard from "../../Icons/Mastercard.svg";
  import PayPal from "../../Icons/PayPal.svg";
  import Visa from "../../Icons/Visa.svg";
  import InlineSVG from "svelte-inline-svg";

  export let iconName: string;
</script>

{#if iconName === "visa"}
  <div class="payment-icon">
    <InlineSVG src={Visa} />
  </div>
{:else if iconName === "mastercard"}
  <div class="payment-icon">
    <InlineSVG src={Mastercard} />
  </div>
{:else if iconName === "discover"}
  <div class="payment-icon">
    <InlineSVG src={Discover} />
  </div>
{:else if iconName === "amex"}
  <div class="payment-icon">
    <InlineSVG src={Amex} />
  </div>
{:else if iconName === "paypal"}
    <InlineSVG id="paypalIcon" src={PayPal} />
{:else}
  {iconName}
{/if}
```

-- PaymentIcon.spec.ts -- 

```
import { render } from "@testing-library/svelte";
import PaymentIcon from "./PaymentIcon.svelte";

describe("tests payment icon snapshots", () => {
  test("should match visa snapshot", () => {
    const props = { iconName: "visa" };
    const { container } = render(PaymentIcon, { ...props });
    expect(container).toMatchSnapshot();
  });
  test("should match mastercard snapshot", () => {
    const props = { iconName: "mastercard" };
    const { container } = render(PaymentIcon, { ...props });
    expect(container).toMatchSnapshot();
  });
  test("should match discover snapshot", () => {
    const props = { iconName: "discover" };
    const { container } = render(PaymentIcon, { ...props });
    expect(container).toMatchSnapshot();
  });
  test("should match amex snapshot", () => {
    const props = { iconName: "amex" };
    const { container } = render(PaymentIcon, { ...props });
    expect(container).toMatchSnapshot();
  });
  test("should match paypal snapshot", () => {
    const props = { iconName: "paypal" };
    const { container } = render(PaymentIcon, { ...props });
    expect(container).toMatchSnapshot();
  });
  test("should match error snapshot", () => {
    const { container } = render(PaymentIcon, { iconName: "" });
    expect(container).toMatchSnapshot();
  });
});
      
```

**Comment by robinscholz** [comment]
Hi @scottdkey 

Could you provide me with a minimal reproduction repo? Seems odd, since this repo uses `@testing-library/svelte` which is dependant on `svelte-jester`.

**Comment by robinscholz** [comment]
@scottdkey Let me know if your problem persists, closing this issue due to inactivity
